#!/usr/bin/env bash
# -*- coding: utf-8 -*- 

_bump() {    
    if [ -z "$1" ]
      then
        # no argument supplied. default to patch increment
        release_string="patch"
    else
        release_string="$1"
    fi

    if mversion ; then
        mversion "$release_string"
    fi
}

main() {
    _ROOT=$(pwd)
    cd ./OpenInk/
    _bump "$1"
    _exit_status="$?"
    cd "$_ROOT"
    exit "$_exit_status"
}

main "$@"
